
sources:
  - name: dbt_demo_source
    database: TEST  
    schema: RAW  
    tables:
      - name: orders
        # config:
        #   freshness:
        #     warn_after:
        #       count: 2
        #       period: day
        #     error_after:
        #       count: 10
        #       period: day
        #   loaded_at_field: 'to_timestamp(load_date)'